BITMAKER-2089 Update issue templates
bitmakerla/estela-cli pull request #20
Opened 2022-10-18 13:15 UTC by raymond1242

2022-11-04 02:14 UTC, Adriana618 approved these changes

2022-11-04 02:19 UTC, Adriana618 requested changes
This branch is same to BITMAKER-2089-3

2022-11-04 11:52 UTC, raymond1242 commented
@Adriana618 I create a new PR with the correct updated file

2022-11-07 17:04 UTC, Adriana618 approved these changes

2022-11-14 23:32 UTC, merged